name: CI/CD de l'application Node.js
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Configuration de Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Mise à jour de la version Node.js

      - name: Installation des dépendances
        run: npm install # Installe toutes les dépendances du package.json

      - name: Démarrage du serveur en arrière-plan
        run: node server.js &

      - name: Attente du démarrage du serveur
        run: sleep 5

      - name: Test de l'endpoint /hello
        id: test_hello
        run: |
          response=$(curl -s http://localhost:3000/hello)
          if [ "$response" = "Hello World!" ]; then
            echo "result=✅ Test de l'endpoint /hello réussi." >> $GITHUB_OUTPUT
          else
            echo "result=❌ Test de l'endpoint /hello échoué." >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Test de l'endpoint /metrics
        id: test_metrics
        run: |
          response=$(curl -s http://localhost:3000/metrics)
          if [[ "$response" == *"hello_requests_total"* ]]; then
            echo "result=✅ Test de l'endpoint /metrics réussi." >> $GITHUB_OUTPUT
          else
            echo "result=❌ Test de l'endpoint /metrics échoué." >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Build Docker image
        run: docker build -t myapp:${{ github.sha }} .

      - name: Save Docker image as artifact
        run: docker save myapp:${{ github.sha }} | gzip > myapp.tar.gz

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: myapp.tar.gz

      - name: Envoi du rapport sur Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          message="Rapport CI/CD :\n${{ steps.test_hello.outputs.result }}\n${{ steps.test_metrics.outputs.result }}"
          curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"$message\"}" "$DISCORD_WEBHOOK"